// 拉勾大前端/07.Part 7 · 商业技术解决方案与高阶技术专题/02.模块二 前端自动化测试专题/00.课程资料/07-02-study-materials/vue-testing-demo/src/components/TodoApp/TodoItem.vue
<template>
  <li data-testid="todo-item" :class="{
    completed: todo.done,
    editing: isEditing
  }">
    <div class="view">
      <input v-model="todo.done" data-testid="todo-done" class="toggle" type="checkbox" />
      <label
        data-testid="todo-text"
        @dblclick="isEditing = true"
      >{{ todo.text }}</label>
      <button
        data-testid="delete"
        class="destroy"
        @click="$emit('delete-todo', todo.id)"
      ></button>
    </div>
    <input
      :value="todo.text"
      v-focus="isEditing"
      class="edit"
      data-testid="todo-edit"
      @blur="isEditing = false"
      @keyup.enter="handleEditTodo"
      @keyup.esc="handleCancelEdit"
    />
  </li>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    todo: {
      type: Object,
      required: true
    }
  },
  directives: {
    focus (element, binding) {
      if (binding.value) {
        element.focus()
      }
    }
  },
  data () {
    return {
      isEditing: false
    }
  },
  methods: {
    handleEditTodo (e) {
      this.$emit('edit-todo', {
        id: this.todo.id,
        text: e.target.value
      })
      // 取消编辑状态
      this.isEditing = false
    },

    handleCancelEdit () {
      this.isEditing = false
    }
  }
}
</script>

// 拉勾大前端/07.Part 7 · 商业技术解决方案与高阶技术专题/02.模块二 前端自动化测试专题/00.课程资料/07-02-study-materials/react-testing-demo/src/TodoItem.js
import React, { useState, useRef } from 'react'
import classNames from 'classnames'

export default function TodoItem ({ todo, doneTodo, removeTodo, saveTodo }) {
  const [isEdit, setIsEdit] = useState(false)
  const inputEl = useRef(null)

  const saveEdit = e => {
    const value = e.target.value.trim()
    if (value.length) {
      saveTodo(todo.id, e.target.value)
    } else {
      removeTodo(todo.id)
    }
    setIsEdit(false)
  }

  const cancelEdit = e => {
    setIsEdit(false)
    e.target.value = todo.text
  }

  return (
    <li className={classNames({
      completed: todo.done,
      editing: isEdit
    })} data-testid="todo-item">
      {/* These are here just to show the structure of the list items */}
      {/* List items should get the class `editing` when editing and `completed` when marked as completed */}
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={todo.done}
          data-testid="todo-done"
          onChange={e => doneTodo(todo.id, e.target.checked)}
        />
        <label
          data-testid="todo-text"
          onDoubleClick={() => {
            setIsEdit(true)
            setTimeout(() => {
              inputEl.current.focus()
            }, 0)
          }}
        >{todo.text}</label>
        <button
          className="destroy"
          data-testid="destroy"
          onClick={() => removeTodo(todo.id)}
        ></button>
      </div>
      <input
        ref={inputEl}
        className="edit"
        autoFocus
        defaultValue={todo.text}
        onBlur={saveEdit}
        data-testid="todo-edit"
        onKeyUp={e => {
          if (e.key === 'Enter') { // 保存编辑
            saveEdit(e)
          } else if (e.key === 'Escape') { // 取消编辑
            cancelEdit(e)
          }
        }}
      />
    </li>
  )
}
