// 拉勾大前端/07.Part 7 · 商业技术解决方案与高阶技术专题/02.模块二 前端自动化测试专题/00.课程资料/07-02-study-materials/react-testing-demo/src/TodoFooter.js
// import classNames from 'classnames'
import { useMemo } from 'react'
import { NavLink } from 'react-router-dom'

export default function TodoFooter ({ todos, removeAllDone, filterText }) {
  const remainingCount = useMemo(
    () => {
      return todos.filter((t) => !t.done).length
    },
    [ todos ]
  )

  return (
    <footer className="footer">
      {/* This should be `0 items left` by default */}
      <span className="todo-count">
        <strong data-testid="remaining">{remainingCount}</strong> item left
      </span>
      {/* Remove this if you don't implement routing */}
      <ul className="filters">
        <li>
          <NavLink activeClassName="selected" exact to="/" data-testid="link-all">
            All
          </NavLink>
        </li>
        <li>
          <NavLink activeClassName="selected" to="/active" data-testid="link-active">
            Active
          </NavLink>
        </li>
        <li>
          <NavLink activeClassName="selected" to="/completed" data-testid="link-completed">
            Completed
          </NavLink>
        </li>
      </ul>
      {/* Hidden if no completed items are left ↓ */}
      {todos.some(t => t.done) ? (
        <button className="clear-completed" data-testid="clear-completed" onClick={removeAllDone}>
          Clear completed
        </button>
      ) : null}
    </footer>
  )
}

// 拉勾大前端/07.Part 7 · 商业技术解决方案与高阶技术专题/02.模块二 前端自动化测试专题/00.课程资料/07-02-study-materials/vue-testing-demo/src/components/TodoApp/TodoFooter.vue
<template>
  <footer class="footer">
    <!-- This should be `0 items left` by default -->
    <span class="todo-count"
      ><strong data-testid="done-todos-count">{{ doneTodosCount }}</strong> item
      left</span
    >
    <!-- Remove this if you don't implement routing -->
    <ul class="filters">
      <li>
        <!-- <a class="selected" href="#/">All</a> -->
        <router-link data-testid="link-all" exact to="/">All</router-link>
      </li>
      <li>
        <!-- <a href="#/active">Active</a> -->
        <router-link data-testid="link-active" to="/active">Active</router-link>
      </li>
      <li>
        <!-- <a href="#/completed">Completed</a> -->
        <router-link data-testid="link-completed" to="/completed">Completed</router-link>
      </li>
    </ul>
    <!-- Hidden if no completed items are left ↓ -->
    <button
      v-if="isClearCompletedShow"
      class="clear-completed"
      data-testid="clear-completed"
      @click="$emit('clear-completed')"
    >Clear completed</button>
  </footer>
</template>

<script>
export default {
  name: 'TodoFooter',
  props: {
    todos: {
      type: Array,
      required: true
    }
  },
  computed: {
    doneTodosCount () {
      return this.todos.filter(t => !t.done).length
    },
    isClearCompletedShow () {
      return this.todos.find(t => t.done)
    }
  }
}
</script>
